name: Restaurant Scraper

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:     # Allows manual triggering

concurrency:
  group: restaurant-scraper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment
        run: |
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "Checking if PAT_TOKEN is set..."
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "Error: PAT_TOKEN is not set"
            exit 1
          else
            echo "PAT_TOKEN is set"
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
        continue-on-error: false

      - name: Verify Git repository
        run: |
          if [ -d ".git" ]; then
            echo "Git repository found"
            git status
          else
            echo "Error: No Git repository found"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox geckodriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright selenium beautifulsoup4
          python -m playwright install --with-deps firefox

      - name: Restore cached progress
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            current_progress.json
            scraped_progress.json
            talabat_restaurants_progress.json
          key: restaurant-scraper-progress-${{ github.run_id }}
          restore-keys: |
            restaurant-scraper-progress-

      - name: Run Talabat scraper
        run: python scraper.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Commit progress updates
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add current_progress.json scraped_progress.json talabat_restaurants_progress.json output/ talabat_restaurants_page_*.json || true
          git commit -m "Update scraper progress and data for run ${{ github.run_id }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }} || echo "Push failed or no changes"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Save progress to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            current_progress.json
            scraped_progress.json
            talabat_restaurants_progress.json
          key: restaurant-scraper-progress-${{ github.run_id }}

      - name: Upload progress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restaurant-progress-files
          path: |
            current_progress.json
            scraped_progress.json
            talabat_restaurants_progress.json
            output/
            menu_debug_*.html
            talabat_restaurants_page_*.json
          retention-days: 7
