name: Restaurant Scraper

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:     # Allows manual triggering

# Concurrency control: Only one run at a time
concurrency:
  group: restaurant-scraper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT for full access
          fetch-depth: 0  # Fetch full history for git operations

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          # Add requests-html if used (uncomment if needed)
          # pip install requests-html

      - name: Restore cached progress
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            current_progress.json
            scraped_progress.json
          key: restaurant-scraper-progress-${{ github.run_id }}
          restore-keys: |
            restaurant-scraper-progress-

      - name: Run Talabat scraper
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use PAT for any API calls

      - name: Commit progress updates
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add current_progress.json scraped_progress.json output/
          git commit -m "Update scraper progress and data for run ${{ github.run_id }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Dataloops-DataEnginner/Restaurants_Scraping_Process.git HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Save progress to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            current_progress.json
            scraped_progress.json
          key: restaurant-scraper-progress-${{ github.run_id }}

      - name: Upload progress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restaurant-progress-files
          path: |
            current_progress.json
            scraped_progress.json
            output/
          retention-days: 7
